// Adds 10 more poems to the curriculum: fetches missing stroke data,
// generates voice clips + stroke rules for new chars, updates registries.
// Usage: node scripts/add-poems.mjs
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const POEMS = [
  {
    title: '憫農',
    author: '李紳',
    lines: ['鋤禾日當午，', '汗滴禾下土。', '誰知盤中餐，', '粒粒皆辛苦。'],
  },
  {
    title: '畫',
    author: '王維',
    lines: ['遠看山有色，', '近聽水無聲。', '春去花還在，', '人來鳥不驚。'],
  },
  {
    title: '江雪',
    author: '柳宗元',
    lines: ['千山鳥飛絕，', '萬徑人蹤滅。', '孤舟蓑笠翁，', '獨釣寒江雪。'],
  },
  {
    title: '一去二三里',
    author: '邵雍',
    lines: ['一去二三里，', '煙村四五家。', '亭台六七座，', '八九十枝花。'],
  },
  {
    title: '詠鵝',
    author: '駱賓王',
    lines: ['鵝鵝鵝，', '曲項向天歌。', '白毛浮綠水，', '紅掌撥清波。'],
  },
  {
    title: '望廬山瀑布',
    author: '李白',
    lines: ['日照香爐生紫煙，', '遙看瀑布掛前川。', '飛流直下三千尺，', '疑是銀河落九天。'],
  },
  {
    title: '回鄉偶書',
    author: '賀知章',
    lines: ['少小離家老大回，', '鄉音無改鬢毛衰。', '兒童相見不相識，', '笑問客從何處來。'],
  },
  {
    title: '楓橋夜泊',
    author: '張繼',
    lines: ['月落烏啼霜滿天，', '江楓漁火對愁眠。', '姑蘇城外寒山寺，', '夜半鐘聲到客船。'],
  },
  {
    title: '尋隱者不遇',
    author: '賈島',
    lines: ['松下問童子，', '言師採藥去。', '只在此山中，', '雲深不知處。'],
  },
  {
    title: '相思',
    author: '王維',
    lines: ['紅豆生南國，', '春來發幾枝。', '願君多採擷，', '此物最相思。'],
  },
];

const poemChars = new Set();
for (const p of POEMS) {
  for (const line of p.lines) {
    for (const ch of line) {
      if (/[\u4e00-\u9fff]/.test(ch)) poemChars.add(ch);
    }
  }
}

const existing = new Set(
  (await readdir('assets/strokes'))
    .filter((f) => f.endsWith('.json'))
    .map((f) => String.fromCodePoint(parseInt(f.replace('.json', ''), 16))),
);

const missing = [...poemChars].filter((ch) => !existing.has(ch));
console.log(`poem chars: ${poemChars.size}, existing: ${existing.size}, missing: ${missing.length}`);
console.log('missing:', missing.join(''));

const outDir = path.resolve('assets/strokes');
for (const ch of missing) {
  const code = ch.codePointAt(0).toString(16).padStart(4, '0');
  const url = `https://unpkg.com/hanzi-writer-data@2.0.1/${encodeURIComponent(ch)}.json`;
  let res;
  for (let i = 0; i < 3; i++) {
    res = await fetch(url);
    if (res.ok) break;
    await new Promise((r) => setTimeout(r, 1500));
  }
  if (!res || !res.ok) {
    console.error(`FAIL ${ch} U+${code}`);
    continue;
  }
  const data = await res.json();
  const slim = { strokes: data.strokes, medians: data.medians };
  await writeFile(path.join(outDir, `${code}.json`), JSON.stringify(slim));
  console.log(`ok ${ch} U+${code} strokes=${data.strokes.length}`);
}

// rebuild characters.ts
const allFiles = (await readdir(outDir)).filter((f) => f.endsWith('.json'));
const entries = allFiles
  .map((f) => {
    const ch = String.fromCodePoint(parseInt(f.replace('.json', ''), 16));
    return `  '${ch}': require('@/assets/strokes/${f}'),`;
  })
  .sort()
  .join('\n');
const registry = `// GENERATED by scripts/fetch-strokes.mjs — do not edit by hand.
// Stroke data: Make-Me-A-Hanzi (Arphic Public License).
import type { CharStrokeData } from '@/lib/types';

export const STROKE_DATA: Record<string, CharStrokeData> = {
${entries}
};
`;
await writeFile(path.resolve('data/characters.ts'), registry);
console.log(`registry: ${allFiles.length} chars`);
