// Downloads stroke-order data (Make-Me-A-Hanzi / hanzi-writer-data, Arphic Public License)
// for every character used in the curriculum and generates data/characters.ts registry.
// Usage: node scripts/fetch-strokes.mjs
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const CHARS = [
  // L1 橫豎
  '一', '二', '三', '十', '土', '王', '上', '工',
  // L2 撇捺
  '人', '八', '大', '天', '木', '禾', '火', '入',
  // L3 點提
  '六', '小', '少', '太', '玉', '主', '江', '河',
  // L4 折
  '口', '日', '目', '月', '田', '山', '白', '石',
  // L5 鉤・綜合
  '了', '子', '手', '力', '水', '心', '也', '我',
  // L6 靜夜思
  '床', '前', '明', '光', '疑', '是', '地', '霜',
  '舉', '頭', '望', '低', '思', '故', '鄉',
  // L7 春曉
  '春', '眠', '不', '覺', '曉', '處', '聞', '啼',
  '鳥', '夜', '來', '風', '雨', '聲', '花', '落',
  '知', '多',
  // L8 登鸛雀樓
  '依', '盡', '黃', '海', '流', '欲', '窮', '千',
  '里', '更', '層', '樓',
];

const unique = [...new Set(CHARS)];
const outDir = path.resolve('assets/strokes');
await mkdir(outDir, { recursive: true });

const entries = [];
for (const ch of unique) {
  const code = ch.codePointAt(0).toString(16).padStart(4, '0');
  const url = `https://unpkg.com/hanzi-writer-data@2.0.1/${encodeURIComponent(ch)}.json`;
  let res = await fetch(url);
  for (let i = 0; i < 3 && !res.ok; i++) {
    await new Promise((r) => setTimeout(r, 1500));
    res = await fetch(url);
  }
  if (!res.ok) {
    console.error(`FAIL ${ch} ${res.status}`);
    continue;
  }
  const data = await res.json();
  const slim = { strokes: data.strokes, medians: data.medians };
  await writeFile(path.join(outDir, `${code}.json`), JSON.stringify(slim));
  entries.push({ ch, code, count: data.strokes.length });
  console.log(`ok ${ch} U+${code} strokes=${data.strokes.length}`);
}

const registry = `// GENERATED by scripts/fetch-strokes.mjs — do not edit by hand.
// Stroke data: Make-Me-A-Hanzi (Arphic Public License).
import type { CharStrokeData } from '@/lib/types';

export const STROKE_DATA: Record<string, CharStrokeData> = {
${entries.map(({ ch, code }) => `  '${ch}': require('@/assets/strokes/${code}.json'),`).join('\n')}
};
`;
await mkdir(path.resolve('data'), { recursive: true });
await writeFile(path.resolve('data/characters.ts'), registry);
console.log(`\nWrote ${entries.length}/${unique.length} chars + data/characters.ts`);
