# Generates bundled Cantonese voice clips (Edge TTS zh-HK-HiuMaanNeural) for
# every char in the curriculum, every stroke name, and praise phrases.
# Output: assets/voice/*.mp3 + data/voice.ts registry.
# Usage: python scripts/gen-voice.py
import asyncio
import json
import re
import sys
from pathlib import Path

import edge_tts

sys.stdout.reconfigure(encoding="utf8", errors="replace")

VOICE = "zh-HK-HiuMaanNeural"
RATE = "-10%"
OUT = Path("assets/voice")

PRAISES = ["寫得好！", "好嘢！", "叻喎！", "做得好啊！"]

# superset of stroke names (overrides + heuristic outputs)
EXTRA_NAMES = [
    "橫", "豎", "撇", "捺", "提", "點", "折", "鉤",
    "橫折", "豎折", "撇折", "橫撇", "橫鉤", "豎鉤", "彎鉤", "臥鉤", "斜鉤",
    "豎彎鉤", "豎提", "橫折鉤", "豎折折鉤", "橫折彎鉤", "撇點", "橫折提",
    "橫折折", "豎折折", "橫折折鉤", "彎",
]


def collect_texts() -> list[str]:
    chars = sorted(
        chr(int(p.stem, 16)) for p in Path("assets/strokes").glob("*.json")
    )
    names = set(EXTRA_NAMES)
    src = Path("data/strokeNames.ts").read_text(encoding="utf8")
    src = re.sub(r"//[^\n]*", "", src)  # strip comments
    for block in re.findall(r"\[([^\]]*)\]", src):
        for m in re.finditer(r"'([^']+)'", block):
            names.add(m.group(1))
    return chars + sorted(names) + PRAISES


async def gen(text: str, path: Path, sem: asyncio.Semaphore) -> bool:
    async with sem:
        for attempt in range(3):
            try:
                communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
                await communicate.save(str(path))
                return True
            except Exception as e:  # noqa: BLE001
                if attempt == 2:
                    print(f"FAIL {text}: {e}")
                    return False
                await asyncio.sleep(1.5)


async def main() -> None:
    OUT.mkdir(exist_ok=True)
    texts = collect_texts()
    print(f"{len(texts)} clips to generate")
    sem = asyncio.Semaphore(4)
    results = await asyncio.gather(
        *(gen(t, OUT / f"{t}.mp3", sem) for t in texts)
    )
    ok = [t for t, r in zip(texts, results) if r and (OUT / f"{t}.mp3").exists()]

    lines = [
        "// GENERATED by scripts/gen-voice.py — do not edit by hand.",
        "// Voice: Microsoft Edge TTS zh-HK-HiuMaanNeural (Cantonese), bundled offline.",
        "export const VOICE_CLIPS: Record<string, number> = {",
    ]
    for t in ok:
        lines.append(f"  {json.dumps(t, ensure_ascii=False)}: require('@/assets/voice/{t}.mp3'),")
    lines.append("};")
    lines.append("")
    Path("data/voice.ts").write_text("\n".join(lines), encoding="utf8")
    print(f"done: {len(ok)}/{len(texts)} clips, registry -> data/voice.ts")


if __name__ == "__main__":
    asyncio.run(main())
