# Generates bundled voice clips (Cantonese + Mandarin) for every char,
# stroke name, and praise phrase. Edge TTS neural voices, no API key.
# Output: assets/voice/yue/*.mp3, assets/voice/cmn/*.mp3 + data/voice.ts
# Usage: python scripts/gen-voice.py
import asyncio
import json
import re
import sys
from pathlib import Path

import edge_tts

sys.stdout.reconfigure(encoding="utf8", errors="replace")

LANGS = {
    "yue": {"voice": "zh-HK-HiuMaanNeural", "rate": "-10%"},
    "cmn": {"voice": "zh-CN-XiaoxiaoNeural", "rate": "-8%"},
}

PRAISES_YUE = ["寫得好！", "好嘢！", "叻喎！", "做得好啊！"]
PRAISES_CMN = ["写得好！", "好耶！", "真棒！", "做得好啊！"]

ERROR_HINTS_YUE = [
    "要由紅點嗰度起筆呀",
    "起筆位置唔啱，再諗下先",
    "寫歪咗，呢筆重新寫",
    "唔夠標準，再寫多次",
    "方向倒轉咗，跟返箭嘴寫",
    "太短啦，寫長少少",
    "未寫完呢筆，繼續",
    "太快啦，慢慢嚟",
]
ERROR_HINTS_CMN = [
    "要从红点那里起笔哦",
    "起笔位置不对，再想想",
    "写歪了，这一笔重新写",
    "不够标准，再写一次",
    "方向反了，跟着箭头写",
    "太短啦，写长一点",
    "还没写完这一笔，继续",
    "太快啦，慢慢来",
]

EXTRA_NAMES = [
    "橫", "豎", "撇", "捺", "提", "點", "折", "鉤",
    "橫折", "豎折", "撇折", "橫撇", "橫鉤", "豎鉤", "彎鉤", "臥鉤", "斜鉤",
    "豎彎鉤", "豎提", "橫折鉤", "豎折折鉤", "橫折彎鉤", "撇點", "橫折提",
    "橫折折", "豎折折", "橫折折鉤", "彎",
]

# Mandarin uses simplified forms for stroke names
NAME_MAP_CMN = {
    "橫": "横", "豎": "竖", "撇": "撇", "捺": "捺", "提": "提", "點": "点", "折": "折", "鉤": "钩",
    "橫折": "横折", "豎折": "竖折", "撇折": "撇折", "橫撇": "横撇", "橫鉤": "横钩", "豎鉤": "竖钩",
    "彎鉤": "弯钩", "臥鉤": "卧钩", "斜鉤": "斜钩", "豎彎鉤": "竖弯钩", "豎提": "竖提",
    "橫折鉤": "横折钩", "豎折折鉤": "竖折折钩", "橫折彎鉤": "横折弯钩", "撇點": "撇点",
    "橫折提": "横折提", "橫折折": "横折折", "豎折折": "竖折折", "橫折折鉤": "横折折钩", "彎": "弯",
}


def collect_texts(lang: str) -> list[str]:
    chars = sorted(chr(int(p.stem, 16)) for p in Path("assets/strokes").glob("*.json"))
    names = set(EXTRA_NAMES)
    src = Path("data/strokeNames.ts").read_text(encoding="utf8")
    src = re.sub(r"//[^\n]*", "", src)
    for block in re.findall(r"\[([^\]]*)\]", src):
        for m in re.finditer(r"'([^']+)'", block):
            names.add(m.group(1))
    if lang == "cmn":
        chars = [c for c in chars]  # chars stay traditional (app is traditional)
        names = {NAME_MAP_CMN.get(n, n) for n in names}
        praises = PRAISES_CMN
        extras = ERROR_HINTS_CMN
    else:
        praises = PRAISES_YUE
        extras = ERROR_HINTS_YUE
    return chars + sorted(names) + praises + extras


async def gen(text: str, path: Path, voice: str, rate: str, sem: asyncio.Semaphore) -> bool:
    async with sem:
        for attempt in range(3):
            try:
                communicate = edge_tts.Communicate(text, voice, rate=rate)
                await communicate.save(str(path))
                return True
            except Exception as e:  # noqa: BLE001
                if attempt == 2:
                    print(f"FAIL [{voice}] {text}: {e}")
                    return False
                await asyncio.sleep(1.5)


async def gen_lang(lang: str, cfg: dict) -> dict:
    out = Path("assets/voice") / lang
    out.mkdir(parents=True, exist_ok=True)
    texts = collect_texts(lang)
    print(f"[{lang}] {len(texts)} clips to generate")
    sem = asyncio.Semaphore(4)
    results = await asyncio.gather(
        *(gen(t, out / f"{t}.mp3", cfg["voice"], cfg["rate"], sem) for t in texts)
    )
    ok = [t for t, r in zip(texts, results) if r and (out / f"{t}.mp3").exists()]
    print(f"[{lang}] done: {len(ok)}/{len(texts)}")
    return {t: f"{lang}/{t}.mp3" for t in ok}


async def main() -> None:
    all_clips = {}
    for lang, cfg in LANGS.items():
        all_clips[lang] = await gen_lang(lang, cfg)

    lines = [
        "// GENERATED by scripts/gen-voice.py — do not edit by hand.",
        "// Cantonese: Edge TTS zh-HK-HiuMaanNeural | Mandarin: zh-CN-XiaoxiaoNeural",
        "export const VOICE_CLIPS: Record<string, Record<string, number>> = {",
    ]
    for lang in ("yue", "cmn"):
        lines.append(f"  {json.dumps(lang)}: {{")
        for text, rel in sorted(all_clips[lang].items()):
            lines.append(f"    {json.dumps(text, ensure_ascii=False)}: require('@/assets/voice/{rel}'),")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    Path("data/voice.ts").write_text("\n".join(lines), encoding="utf8")
    total = sum(len(v) for v in all_clips.values())
    print(f"registry -> data/voice.ts ({total} clips total)")


if __name__ == "__main__":
    asyncio.run(main())
